##########################################
# Site Settings
baseURL = "https://throwaway1312.github.io"
title = "infoGBB"
subtitle = "Contenitore comunicati Curva Sud Ambrì"
languageCode = "it"

# Name of theme
theme = "strange-case"
colorScheme = "scheme-darkbrown"
    
# `hugo new` automatically opened text editor
newContentEditor = "vim"

# Text to display for footnote return links
footnoteReturnLinkContents = "↩"

# Enable `.GitInfo` object for each page?
enableGitInfo = false

# Enable generation of `robots.txt` file?
enableRobotsTXT = true

# Number of items per page in paginated 
# lists (valid for the `posts` homepage
# layout in MemE)
paginate = 10

# URL related
disablePathToLower = false
relativeURLs = false
uglyURLs = false

[author]
    # Name
    name = "infogbb"
    # Email
    email = "test@test.ch"
    # Motto or introduction
    motto = "test"

## Main menu
[[menu.main]]
    url = "/"
    name = "Comunicati"
    weight = 100
    identifier = "posts"
[[menu.main]]
    url = "/sgambetto/"
    name = "Lo Sgambetto"
    weight = 200
[[menu.main]]
    url = "/solidarieta/"
    name = "Solidarietà"
    weight = 300
[[menu.main]]
    name = "Contatto"
    url = "/contatto/"
    weight = 400


# Theme Settings
[params]
    ######################################
    # Atom & RSS

    # Include full content?
    includeContent = true
    # Note: If false, only the summary of
    #       the post will be included. The
    #       summary, Hugo automatically
    #       takes the first 70 words (you
    #       can customize this via
    #       `summaryLength`) of your content
    #       as its summary by default.
    #       Alternatively, you may use the
    #       <!--more--> (with no whitespace)
    #       summary divider to split summary
    #       manually. Or use the `summary`
    #       variable in post’s Front
    #       Matter to assign it manually.
    #       The priority of them: assign
    #       manually > split manually >
    #       split automatically. Additionally,
    #       `description` in post’s Front
    #       Matter has a higher priority
    #       than assign manually in the
    #       custom Atom & RSS template of
    #       MemE.


    ######################################
    # Post Settings

    # The color change duration of the
    # hyperlink (in seconds)
    duration = 0.5

    # Primary color of light mode
    primaryColorLight = "220, 90%, 56%"
    # Primary color of dark mode
    primaryColorDark = "201, 65%, 62%"
    # ATTENTION: only HSL color values ​​are
    #            supported

    # The content width of the post
    postWidth = 32
    # Note: you can leave it empty("") to
    #       fallback to the default value: 42
    #       Unit: em

    # Is the post original?
    original = true
    # Note: will affect the author and
    #       copyright information of the
    #       post
    #       *global settings*
    #       `original` in post’s Front Matter
    #       has a higher priority than here


    ######################################
    # Post Description

    displayPostDescription = true


    ######################################
    # Post Meta Info

    enablePostMeta = true
    # Note: *global settings*
    #       `meta` in post’s Front Matter
    #       has a higher priority than here

    enablePostMetaInHome = true
    # Note: valid for the `posts` and
    #       `page` homepage layout only

    postMetaDateFormat = "2.1.2006"
    # ATTENTION: be sure to follow the
    #            specified format
    #            https://gohugo.io/functions/format/

    displayPublishedDate = true
    publishedDateIcon = "calendar-alt"

    displayModifiedDate = false
    modifiedDateIcon = "calendar-check"

    displayExpiredDate = false
    expiredDateIcon = "calendar-times"

    displayCategory = true
    categoryIcon = "folder"
    categoryDelimiter = "/"

    displayWordCount = false
    wordCountIcon = "pencil-alt"

    displayReadingTime = false
    readingTimeIcon = "clock"

    displayBusuanziPagePV = false
    busuanziPagePVIcon = "eye"
    # Note: render only in production
    #       environment
    #       Homepage is not supported yet
    #       https://busuanzi.ibruce.info/


    ######################################
    # Markdown Related

    # Open external links in a new tab?
    hrefTargetBlank = true

    # Compatibility with LaTeX?
    compatibleWithLaTeX = false


    ######################################
    # Table of Contents

    enableTOC = false
    # Note: *global settings*
    #       `toc` in post’s Front Matter
    #       has a higher priority than here

    displayTOCTitle = true

    linkHeadingsToTOC = true


    ######################################
    # Headings Anchor

    enableHeadingsAnchor = true

    # Level range of headings
    headingsOpt = "1-6"
    # Note: regex format, default value
    #       is 1-6, which is 1|2|3|4|5|6,
    #       which is h1 to h6.

    anchorSymbol = "#"
    # Note: the anchorIcon has a higher
    #       priority than anchorSybol
    #       Default: §

    anchorIcon = "link"
    # Note: you can leave it empty("") to
    #       fallback to the anchorSymbol

    enableAnchorLink = true

    enableAnchorAutoHide = true


    ######################################
    # Caption

    enableCaption = true

    captionPrefix = "◎ "


    ######################################
    # Image Hosting

    # Note: render only in production
    #       environment
    #
    #       only support absolute URLs
    #       relative to root, e.g.
    #       /images/meme.jpg
    #       (~/blog/static/images/meme.jpg)

    enableImageHost = false

    imageHostURL = "https://example.com/"

    # Replace the image link in the HTML
    # head meta also?
    headAlso = false


    ######################################
    # Video Hosting

    # Note: render only in production
    #       environment
    #
    #       only support absolute URLs
    #       relative to root, e.g.
    #       /videos/meme.mp4

    enableVideoHost = false

    videoHostURL = "https://example.com/"


    ######################################
    # Footnotes

    # Use the square brackets to wrap
    # the reference number?
    squareBrackets = true

    # Replace the text in footnote return
    # link with icon?
    footnoteReturnLinkIcon = "angle-up"
    # Note: will replace
    #       `footnoteReturnLinkContents`
    #       with icon if it’s not
    #       empty("")

    # Insert horizontal rule by yourself?
    insertHrBySelf = true
    # Note: If true, the automatically
    #       generated horizontal rule
    #       (<hr>) will be removed. In
    #       fact, the horizontal rule you
    #       added will be removed. This
    #       option is very useful if you
    #       prefer to add `---` to separate
    #       the content from the footnote
    #       in the Markdown file.


    ######################################
    # Typography

    ######################################
    ## Font Family

    # Note: any option is empty(""),
    #       fallback to `fontFamilyBody`
    #       it will. Therefore, it is not
    #       necessary to set all.
    #       Additionally, you can leave
    #       `fontFamilySiteBrand` empty("")
    #       if you use SVG as your site
    #       brand.

    # Site brand
    fontFamilySiteBrand = ""
    # Menu bar
    fontFamilyMenu = ""
    # Post title, post subtitle, list title, year and month title of the list, related posts title, previous/next post title, header of table, term/name in a definition list
    fontFamilyTitle = "Comfortaa, sans-serif"
    # Headings, toc title
    fontFamilyHeadings = "Comfortaa, sans-serif"
    # Code, superscript, post meta info, post updated badge, post gitinfo, minimal footer, busuanzi site view counter
    fontFamilyCode = "'Source Code Pro', monospace"
    # Blockquotes
    fontFamilyQuote = ""
    # Table of contents
    fontFamilyTOC = ""
    # Caption
    fontFamilyCaption = ""
    # Footer
    fontFamilyFooter = ""
    # Body
    fontFamilyBody = "'IBM Plex Serif', serif"

    # Embed fonts link
    fontsLink = ""
    # Note: In order for the reader to
    #       experience the fonts you set,
    #       it is best to use web fonts.
    #       MemE currently only supports
    #       Google Fonts, please go to
    #       https://fonts.google.com/ to
    #       get the link. If this is left
    #       empty(""), web fonts will not
    #       be used.

    ######################################
    ## Font Size (unit: px)

    fontSize = 20

    ######################################
    ## Tab Size

    tabSize = 4

    ######################################
    ## Line Height

    lineHeight = 1.618
    # Note: apply to post paragraph & toc
    #       only

    ######################################
    ## Paragraph Indents

    enableParagraphIndent = true

    indentFirstParagraph = false
    # Note: *global settings*
    #       `indentFirstParagraph` in post’s Front Matter
    #       has a higher priority than here

    paragraphStyle = "margin"
    # Note: margin or indent
    #       *global settings*
    #       `indent` in post’s Front Matter
    #       has a higher priority than here

    ######################################
    ## Text Justification

    enableJustify = false
    # Note: *global settings*
    #       `align` in post’s Front Matter
    #       has a higher priority than here

    ######################################
    ## Drop Cap

    enableDropCap = false
    # Note: *global settings*
    #       `dropCap` in post’s Front Matter
    #       has a higher priority than here

    # Enable drop cap after every
    # horizontal rule tag?
    enableDropCapAfterHr = false
    # Note: *global settings*
    #       `dropCapAfterHr` in post’s Front Matter
    #       has a higher priority than here

    # Delete horizontal rule tag before
    # drop cap?
    deleteHrBeforeDropCap = false
    # Note: *global settings*
    #       `deleteHrBeforeDropCap` in post’s Front Matter
    #       has a higher priority than here

    ######################################
    ## Small Caps

    enableSmallCaps = false
    # Note: apply to headings & post toc
    #       title only
    #       *global settings*
    #       `smallCaps` in post’s Front Matter
    #       has a higher priority than here

    ######################################
    # Post Copyright

    enablePostCopyright = false

    displayPostCopyright = false
    # Note: *global settings*
    #       `displayCopyright` in post’s Front Matter
    #       has a higher priority than here


    ######################################
    # Post Updated Badge

    enablePostUpdatedBadge = false

    displayUpdatedBadge = false
    # Note: *global settings*
    #       `badge` in post’s Front Matter
    #       has a higher priority than here

    # Add `title` attribute?
    enableBadgeTitle = true
    badgeTitlePrefix = "Updated @ "


    ######################################
    # Post Gitinfo

    enablePostGitInfo = false

    displayPostGitInfo = false
    # Note: *global settings*
    #       `gitinfo` in post’s Front Matter
    #       has a higher priority than here

    repoURL = ""
    repoEditURL = ""

    gitIcon = "code-branch"
    displayCommitHash = true

    displayCommitMessage = true
    msgIcon = "info"

    displayFeedback = true
    feedbackIcon = "question"
    feedbackText = "Feedback"

    displayEditLink = true
    editIcon = "edit"
    editText = "Edit Me?"


    ######################################
    # Related Posts

    enableRelatedPosts = true

    displayRelatedPosts = true
    # Note: *global settings*
    #       `related` in post’s Front Matter
    #       has a higher priority than here

    relatedPostsNumber = 5

    relatedPostsIcon = "plus-circle"


    ######################################
    # Post Tags

    enablePostTags = true

    postTagsIcon = "tag"


    ######################################
    # Previous/Next Post

    # Note: In MemE, it is designed from a
    #       spatial perspective rather
    #       than a time perspective like
    #       most other themes do.
    #       Therefore, you will get a
    #       newer post if you click prev
    #       on the left; you will get an
    #       older post if you click next
    #       on the right.

    enablePostNav = true

    # Apply to posts that below the same
    # top level section only?
    postNavInSection = true


    ######################################
    # Minimal Footer

    enableMinimalFooter = false
    enableVerticalBarStructure = false
    # Note: If you enable this, the
    #       categories or sections that
    #       displayed on the right will
    #       include all top-level
    #       categories or sections and are
    #       separated by vertical bar(|).

    enableAboutPageMinimalFooter = false


    ######################################
    # Back to Top

    enableBackToTop = true

    enableBackToTopAutoHide = true

    displayBackToTopInHome = true

    backToTopIcon = "arrow-up"
    ######################################
    # Footer

    enableFooter = false
    ######################################
    # Multilingual

    enableLangToggle = true

    hideLangToggleInHome = false

    autoHideLangToggle = false
    # Note: in other words, the toggle is
    #       displayed only when the post
    #       has a translated version


    ######################################
    # Syntax Highlighting

    enableHighlight = true

    ######################################
    # Fingerprinting and SRI

    enableFingerprint = false

    ######################################
    # Force HTTPS Redirection

    # Note: render only in production
    #       environment

    enableForceHTTPS = false
    # Note: use JavaScript for redirection.
    #       You can enable this if your
    #       server does not support forced
    #       HTTPS.


    ######################################
    # Smooth Scroll

    enableSmoothScroll = true
    # Note: https://github.com/cferdinandi/smooth-scroll


    ######################################
    # Medium Zoom

    enableMediumZoom = false
    # Note: https://github.com/francoischalifour/medium-zoom


    ######################################
    # 404 Page

    fofPoster = ""

    fofVideoWebm = ""
    fofVideoMp4 = ""
    # Note: you can leave these two
    #       options empty("")
